[project]
name = "project-footprint-geo-allocation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.1.2",
    "pandas>=3.0.1",
    "pathlib>=1.0.1",
]
